name: EngineerMemo

options:
  bundleIdPrefix: com.yossibank
  developmentLanguage: ja
  deploymentTarget:
    iOS: 14.0

settings:
  base:
    MARKETING_VERSION: 1.0.0
    CURRENT_PROJECT_VERSION: 1
  configs:
    debug:
      DEBUG_INFORMATION_FORMAT: "dwarf-with-dsym"

packages:
  UIKitHelper:
    url: https://github.com/yossibank/UIKitHelper.git
    from: 0.4.4
  firebase-ios-sdk:
    url: https://github.com/firebase/firebase-ios-sdk.git
    from: 10.0.0
  IQKeyboardManager:
    url: https://github.com/hackiftekhar/IQKeyboardManager
    from: 6.5.0
  OHHTTPStubs:
    url: https://github.com/AliSoftware/OHHTTPStubs.git
    from: 9.1.0
  ios-snapshot-test-case:
    url: https://github.com/uber/ios-snapshot-test-case
    from: 8.0.0

targets:
  EngineerMemo:
    type: application
    platform: iOS
    sources:
      - EngineerMemo
    settings:
      base:
        DEVELOPMENT_LANGUAGE: jp
        INFOPLIST_PREPROCESS: Yes
        INFOPLIST_FILE: EngineerMemo/App/Plist/Info.plist
        OTHER_LDFLAGS: $(inherited) $(OTHER_LDFLAGS) -ObjC
      configs:
        debug:
          ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon.dev
          OTHER_SWIFT_FLAGS: $(inherited) -Xfrontend -warn-long-expression-type-checking=500 -Xfrontend -warn-long-function-bodies=500
          PRODUCT_BUNDLE_IDENTIFIER: com.yossibank.EngineerMemo.dev
        release:
          ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
          PRODUCT_BUNDLE_IDENTIFIER: com.yossibank.EngineerMemo
    dependencies:
      - package: UIKitHelper
      - package: firebase-ios-sdk
        product: FirebaseAnalyticsWithoutAdIdSupport
      - package: firebase-ios-sdk
        product: FirebaseCrashlytics
      - package: IQKeyboardManager
        product: IQKeyboardManagerSwift
    preBuildScripts:
      - name: Setup GoogleServiceInfoPlist
        basedOnDependencyAnalysis: false
        path: ./Scripts/Firebase/infoplist.sh
      - name: Setup LicensePlist
        basedOnDependencyAnalysis: false
        path: ./Scripts/XcodeGen/licensePlist.sh
      - name: Get CommitHash
        basedOnDependencyAnalysis: false
        path: ./Scripts/XcodeGen/commitHash.sh
        inputFiles:
          - ${TEMP_DIR}/Preprocessed-Info.plist
      - name: Generate Mock
        basedOnDependencyAnalysis: false
        path: ./Scripts/XcodeGen/mockolo.sh
        outputFiles:
          - EngineerMemoTests/TestMock/MockResults.swift
      - name: Run SwiftFormat
        basedOnDependencyAnalysis: false
        path: ./Scripts/XcodeGen/swiftformat.sh
      - name: Run SwiftGen
        basedOnDependencyAnalysis: false
        path: ./Scripts/XcodeGen/swiftgen.sh
    postCompileScripts:
      - name: Run SwiftLint
        basedOnDependencyAnalysis: false
        path: ./Scripts/XcodeGen/swiftlint.sh
    postBuildScripts:
      - name: Run Crashlytics
        basedOnDependencyAnalysis: false
        path: ./Scripts/Firebase/crashlytics.sh
        inputFiles:
          - ${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}/Contents/Resources/DWARF/${TARGET_NAME}
          - $(SRCROOT)/$(BUILT_PRODUCTS_DIR)/$(INFOPLIST_PATH)

  EngineerMemoTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - EngineerMemoTests
    settings:
      base:
        INFOPLIST_FILE: EngineerMemoTests/Info.plist
    dependencies:
      - target: EngineerMemo
      - package: OHHTTPStubs
        product: OHHTTPStubsSwift
      - package: ios-snapshot-test-case
        product: iOSSnapshotTestCase

  EngineerMemoUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - EngineerMemoUITests
    settings:
      base:
        INFOPLIST_FILE: EngineerMemoUITests/Info.plist
    dependencies:
      - target: EngineerMemo

schemes:
  EngineerMemo:
    build:
      targets:
        EngineerMemo: all
        EngineerMemoTests: [test]
        EngineerMemoUITests: [test]
    run:
      config: Debug
      commandLineArguments:
        "-FIRDebugEnabled": false
        "-FIRDebugDisabled": true
        "-FIRAnalyticsDebugEnabled": false
    test:
      config: Debug
      gatherCoverageData: true
      targets:
        - name: EngineerMemoTests
          parallelizable: false
          randomExecutionOrder: true
      environmentVariables:
        FB_REFERENCE_IMAGE_DIR: $(SOURCE_ROOT)/$(PROJECT_NAME)Tests/TestSnapshot/ReferenceImages
        IMAGE_DIFF_DIR: $(SOURCE_ROOT)/$(PROJECT_NAME)Tests/TestSnapshot/FailureDiffs
      language: ja
      region: JP
      testPlans:
        - path: EngineerMemoTests/EngineerMemo.xctestplan
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release