# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "100"
ENV["FASTLANE_XCODEBUILD_SETTINGS_RETRIES"] = "10"

default_platform(:ios)

platform :ios do
  desc "ユニットテストを実行する"
  lane :unit_test do
    scan(
      project: 'EngineerMemo.xcodeproj',
      scheme: "EngineerMemo",
      testplan: "EngineerMemo",
      device: "iPhone 14 (16.0)",
      configuration: "Debug",
      cloned_source_packages_path: "SourcePackages",
      derived_data_path: "DerivedData",
      result_bundle: true,
      output_directory: "EngineerMemoXCResult"
    )
  end
end