ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "100"
ENV["FASTLANE_XCODEBUILD_SETTINGS_RETRIES"] = "10"

default_platform(:ios)

platform :ios do
  desc "ユニットテストを実行する"
  lane :unit_test do
    scan(
      project: 'EngineerMemo.xcodeproj',
      scheme: "EngineerMemo",
      testplan: "EngineerMemo",
      configuration: "Debug",
      device: "iPhone 14",
      result_bundle: true,
      output_directory: "Test",
      derived_data_path: "DerivedData",
      cloned_source_packages_path: "SourcePackages",
      clean: true
    )
  end
end